service: my-mastadon

provider:
  name: aws
  runtime: nodejs6.10
  apiKeys:
    - mastadon1
  usagePlan:
    quota:
      limit: 2000
      period: MONTH

functions:
  feed:
    handler: handler.feed
    description: Mastadon feed
    events:
      - http:
          path: feed
          method: get
          cors: true
          private: true
